title: TEXTMYAGENT
description: Your AI Executive Assistant, Available via iMessage
baseurl: ""
url: "https://imessage.lol"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - logs/
  - archive/
  - "*.md"
  - README.md

# Include HTML files
include:
  - index.html
